export enum VoiceLanguage {
  EnglishAustralia = "English (Australia)",
  EnglishCanada = "English (Canada)",
  EnglishHongKong = "English (Hong Kong)",
  EnglishIndia = "English (India)",
  EnglishIreland = "English (Ireland)",
  EnglishKenya = "English (Kenya)",
  EnglishNewZealand = "English (New Zealand)",
  EnglishNigeria = "English (Nigeria)",
  EnglishPhilippines = "English (Philippines)",
  EnglishSingapore = "English (Singapore)",
  EnglishSouthAfrica = "English (South Africa)",
  EnglishTanzania = "English (Tanzania)",
  EnglishUnitedKingdom = "English (United Kingdom)",
  EnglishUnitedStates = "English (United States)",
}

export enum VoiceBaseLanguage {
  EnglishAustralia = "english",
  EnglishCanada = "english",
  EnglishHongKong = "english",
  EnglishIndia = "english",
  EnglishIreland = "english",
  EnglishKenya = "english",
  EnglishNewZealand = "english",
  EnglishNigeria = "english",
  EnglishPhilippines = "english",
  EnglishSingapore = "english",
  EnglishSouthAfrica = "english",
  EnglishTanzania = "english",
  EnglishUnitedKingdom = "english",
  EnglishUnitedStates = "english",
}